language: node_js
node_js:
- '4'
branches:
    only: master
before_script:
- npm install -g gulp
- npm install -g bower
- bower install
script: bash ./deploy.sh
env:
    global:
    - GH_REF: github.com/jonatasleon/tracker-movies.github.io.git
    - secure: "VQ3uLovXDjrbly4DflEZQZEUEx9j4fwYJCR/FQZpU+vCSbCM/4C+wA2IZSlBBoiTPuBIcuFtGfmJ0zK0ULySh+WlG3471pybMT89pkI4yT3EeTlPN+mE0mjz8GdWX4Iz0/zdLcAX/kuh7iHy/cgFn14aUuSIPBnQp2C/s+yclUzCmCHKbFXzKj+I1FJHgUI9nYIwCzgwxXTJRq2k5Hcfc6VgaJ5yKxHcQoMXxgzdUyRrmkR9qEC3Z5KzuJR5eOeqiGnv9dEEelWtuEsXcK3U2rmeBQxojJqNLizGPS5v2I2hlrZORMLQ8gAjizqjEsPR4ze4cXmCta8vRR8ojNRXAOxud19F3CLpyWzfrLCUBNhbcPNbzUdcW7JwZ1LWiVowfISxV5kXEJMXXibU1aduCRAH9BlIyz+DI8A1Qw038E8s4Gx+6pZ5XOt7RfOqiBRB6nO/uP4vhYqfrwa1gCvQR1uRgiuOWxZzkSPtS1GJXsvvFJZC6G7NhnHUifilqGDKEGAIpY+mT2A4eZk7BpIc5dws1kqSfT95XVj5z4+Kl5TAH8rwgcgkhFqG5EjaLcePL+wjVpx38ig9J4Se0jcOSYzrlDK9F9MV3+rKaDcI2GHaOGX3rc3HlsInFsMWnNw81mstTVJkOJbsKoqNtfODD+X8J4G5UYsMHlqwcj5DRAU="
